### ISSUE TITLE
Spotify-Alexa Adapter 

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1752]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am using avs-device-sdk-1.18 Spotify ESDK Adapter-3.122.67 and **Adapter v.1.8**. I an getting compilation errors. Kindly confirm these are the compatible versions or not.

## What is the expected behavior?
Adapter should be complied and do not throw missing member errors.

## Provide the steps to reproduce the issue, if applicable:
use avs-device-sdk-1.18
Spotify ESDK-3.122.67
Adapter v1.8
Try to compile these three things.
Logs are attached.

### What version of the AVS Device SDK are you using?
     avs-device-sdk-1.18

### Tell us what hardware you're using:
Linux-Ubuntu 16.04

### Tell us about your OS (Type & version):
[spotify_alexa_compile_logs.txt](https://github.com/alexa/avs-device-sdk/files/4906549/spotify_alexa_compile_logs.txt)
 Linux

**Comment by Alexa-AUH** [comment]
**Adapter :- Spotify-1.8.1.tar.gz**

**Comment by alexandrekm-amzn** [comment]
hi @Alexa-AUH 
it's known to work with SDK 1.18 and Spotify ESDK v3.34b or SDK 1.20 and Spotify EDSK v3.114.42.
Can you try with one of those combinations and report back?

**Comment by Alexa-AUH** [comment]
I am able to compile SDK 1.18 + Adapter Spotify-1.8.1 + ESDK v3.99 by neglecting one error.

**Comment by kclchan** [comment]
Glad that it works for you.  Closing the issue now.
